import Navbar from "../component/Navbar"
import 'bootstrap/dist/css/bootstrap.css'
import "./custom.css"
import { ContextProvider } from "@/component/context/DataProvider"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar/>
        <ContextProvider>
        {children}
        </ContextProvider>
      </body>
    </html>
  )
}
